// Copyright (c) Meta Platforms, Inc. and affiliates.

// Generated by tools/gen_sheet_anim.py from spritesheet.webp. Do not edit.
#pragma once

#include <stdint.h>
#include "sdkconfig.h"

#define HAPPY_ANIM_WIDTH     176
#define HAPPY_ANIM_HEIGHT    200
#define HAPPY_ANIM_FRAMES    74
#define HAPPY_ANIM_FRAME_MS  120

#if CONFIG_HOMEHUB_DISPLAY
extern const uint16_t happy_anim_palette[128];
extern const uint8_t happy_anim_frames[HAPPY_ANIM_FRAMES][HAPPY_ANIM_HEIGHT * HAPPY_ANIM_WIDTH];
#endif
